import { getPresetById } from '$lib/stores/nlcaPrompt.svelte.js';
import type { ExperimentConfig } from './types.js';

interface ExperimentLike {
	id: string;
	label: string;
	config: ExperimentConfig;
}

const MAX_TASK_PREVIEW = 60;

/**
 * Compute the user-facing display name for an experiment.
 *
 * Priority:
 *   1. The preset `name` when `promptPresetId` points to a known preset
 *      (e.g. "Face: Robot" instead of the task's first paragraph).
 *   2. A trimmed, non-auto-generated stored label (skips the legacy
 *      "[SN] <first-line-of-task> · model · 50×50" format).
 *   3. The first line of the task description, truncated to ~40 chars.
 *   4. "Exp <short-id>" as a last resort.
 *
 * Derived at render time so loaded experiments with stale auto-labels
 * immediately show the clean preset name once `promptPresetId` is in
 * their config.
 */
export function experimentDisplayName(exp: ExperimentLike): string {
	const presetId = exp.config.promptPresetId;
	if (presetId) {
		const preset = getPresetById(presetId);
		if (preset?.name) return preset.name;
	}

	const label = exp.label?.trim() ?? '';
	if (label && !isAutoGeneratedLabel(label)) {
		return label;
	}

	const firstLine = (exp.config.taskDescription ?? '').split('\n')[0]?.trim() ?? '';
	if (firstLine) {
		return firstLine.length > MAX_TASK_PREVIEW
			? firstLine.slice(0, MAX_TASK_PREVIEW - 1) + '…'
			: firstLine;
	}

	if (label) return label;

	return `Exp ${exp.id.slice(0, 6)}`;
}

/** The old `generateLabel()` shape — `[OR]|[SN] <task> · <model> · WxH`. */
function isAutoGeneratedLabel(label: string): boolean {
	return /^\[(OR|SN)\]\s/.test(label);
}
